### PR TITLE
Add IssueType filter to the overview card

### PR DESCRIPTION
**Pull request by mcalus3**
Technically speaking, I could add an expanding panel with some label like "show empty issue types", but I wanted to maintain as much visual simplicity as i could - in the end it's an overview widget and it shouldn't be used to generate reports, rather get the most valuable piece of the info.

I've implemented showing non-empty ones by default and an ability to switch it by the user to "all". The setting will be stored in local storage so it wouldn't be necessary to toggle it every time user opens the browser.

https://www.loom.com/share/d652cf4430f840e3b78a8153676ea342

### CODE REVIEW

**Comment by mcalus3** [comment]
When working with component system I have to work with limited set of UI primitives (that's not necessary a drawback - users are already familiar with those so they will have easier time learning it). Only two options that come to my mind are: _expanding panel_ and the _permanent (localStorage) toggle in the "more options" menu_.

Knowing our requirements:

1 - not cluttering the UI with information that is not relevant 99% of times - because it's an overview card,
2 - being able to switch between two views

we have to choose based on their drawbacks:

- _permanent (localStorage) toggle_ - It feels like an "overkill" to have a permanent option
- _expanding panel_ - cluttering of the ui

I don't want to come up with any other solution (like _toggle-expand-in-the-menu chimera_) for the sake of user familiarity with known primitives. And from the two above, I choose _permanent (localStorage) toggle_ - it's workings are familiar for users and somewhat fulfills all requirements

It's tempting to solve UI problems with components that just straightforward address the case, but it's better for the user to have the one that is closest from the set of things he already is familiar with.

**Comment by martina-if** [comment]
I like the local storage option. One tweak to that could be to always display the basic types (story, bug and task) regardless or the count.

But I'm not a UI expert, someone with more knowledge should weight in :)

Another question is: would the storage be per component or global for all components?

**Comment by mcalus3** [comment]
@martina-if In my opinion it would be simpler if it won't be per-component, but global. And in case of the basic types - there could be projects that didn't even have them, so I don't think that they should have any "special treatment" in our widget if they don't have in JIRA.

**Review by iain-b — DISMISSED** [review]
Lgtm, thanks, Marek.

**Review by iain-b — APPROVED** [review]

**Comment by O5ten** [comment]
🥳

**Pull request merged**
