### PR TITLE
Implementation proposal to manage excessive numbers on Jira Card.

### PR DESCRIPTION
**Pull request by Xantier**
Issue: https://github.com/RoadieHQ/backstage-plugin-jira/issues/58

* Adding filter to by default not display status category "Done":
image

* Adding functionality to retrieve possible JQL queries from annotation and displaying numbers based on those instead of default queries:
Backstage entity annotation:
```
    jira/project-key: TEST
    jira/queries-Query1: project = "TEST" AND issuetype = "Story" AND statuscategory not in ("Done")
```
-->
image

Not certain if we are abusing the system by overloading annotations with extra data. (They are all restricted to be strings)

### CODE REVIEW

**Comment by dtuite** [comment]
@Xantier I can't think of a reason why someone would ever want to see the total number of "Done" JIRAs. Can we just remove that option entirely?

**Comment by Xantier** [comment]
> @Xantier I can't think of a reason why someone would ever want to see the total number of "Done" JIRAs. Can we just remove that option entirely?

Yup, that makes sense to me. I need to dig through Jira documentation so that we are we certain that the status category is the way to go here.

**Comment by dtuite** [comment]
I agree with the suggested concern about annotation abuse. @adamdmharvey do you see a need to support completely customizable queries like the above example? I'm inclined to keep it simple as much as possible.

@Xantier Can we remove the Sub-task figure too please? Sub-tasks are quite a fine-grained measure and don't make sense in this context (I realise you didn't add them).

**Comment by Xantier** [comment]
> @Xantier Can we remove the Sub-task figure too please? Sub-tasks are quite a fine-grained measure and don't make sense in this context (I realise you didn't add them).

That would be an addition of logic in this case. Those types are automatically fetched and used as sources from the Jira project.

**Comment by dtuite** [comment]
> > @Xantier Can we remove the Sub-task figure too please? Sub-tasks are quite a fine-grained measure and don't make sense in this context (I realise you didn't add them).
> 
> That would be an addition of logic in this case. Those types are automatically fetched and used as sources from the Jira project.

Ah. Ok. In that case let's leave it as it is.

**Comment by dtuite** [comment]
I'll defer code review to @iain-b.

Product wise, I think it would make sense to

1. Split the functionality for arbitrary JQL queries into a separate pull request so we can debate whether or not people are going to shoot themselves in the foot without blocking the easier change.
2. Remove the option to view "Done" JIRAs completely. I don't believe it makes sense as a use case.

**Comment by dtuite** [comment]
By the way, there is discussion about this on the Roadie Discord channel if you haven't seen it.

https://discord.com/channels/760879902391009330/760879902391009333/812215403572494377

**Comment by adamdmharvey** [comment]
I like the idea; I think it's also a slipperly slope to undue complexity.

Including the use of `JQL` conceptually makes sense. Some teams may have subtasks, some might not. Some teams use them in one way, some another. But the issue types depending on the instance could be wildly complicated.  Given that, I feel like it could be a bit overkill for the need, leading to abuse or complexity introduced intentionally or by accident from the entity owner.  If we think of a Backstage instance with a single integrator team, allowing JQL to be defined in the `catalog-info.yaml` itself elevates that not to a central integration team who control the installation of the plugin and it's connectivity to the Jira API, but now instead to 100 different unique teams who al ldefine their own decentralized catalog-info.yaml's for their individual components. How many would understand exactly how to write the proper JQL to only elevate just the relevant issue types needed for this query which is ONLY used to count? Where would you put the documentation for this, again not for your integrator, but for these hundreds of people at your ocmpany?  point them all to Roadie's documentation?

I could guess they could tweak the JQL to mistakenly return other things even beyond issue types, or just to wildly complicate the JQL making it slow.

So my _initial reaction_ is while a really neat implementation idea, I feel like it would be introducing too much complexity or risk for the end-user using it.  But I'd be happy to think further on it and open to other ideas!  😁

**Comment by adamdmharvey** [comment]
I'll note, my previous chat on Discord with the team was trying to elude to I believe Atlassian has a higher level concept of "resolved" or "unresolved" issues.  These are ways to GROUP issue types, without actually SPECIFYING them, and in that resolution case involves the setting of a value in a specific field.  But I thought there was another high-level concept of "closed/done" - and I'll admit to forgetting what it's called - but trying to use those higher-level concepts to say "show all the stuff that's not done/closed" isn't the same thing as saying `where issueType not in (done, closed, terminated, rejected, blah blah blah)` where you have to list literally every single issue time which might POSSIBLY be closed. I thought the system knew it somehow but again without diving into the vendor doco I forget off hand!

**Comment by Xantier** [comment]
I've removed the JQL portion from this. We can revisit that at a later time. Just hardcoding the status category to be not 'Done' to remove open tickets from the numbers.

**Review by dtuite — APPROVED** [review]

**Pull request merged**
